#include "stdio.h"
#include "string.h"
#include "gxota.h"
#include "version_autogenerated.h"
#include "boot.h"
#include "load_kernel.h"
#include "flash.h"
#include "libini.h"

#if 1
#define GXOTA_DBG(...)                printf( __VA_ARGS__)
#else
#define GXOTA_DBG(...)
#endif

#define OEM_UPDATE_SECTION              ("update")
#define OEM_UPDATE_FLAG                 ("flag")
#define OEM_UPDATE_VARIABLE             ("yes")

#define OTA_FIND_START_ADDR          		0x10000
#define OTA_FIND_STEP                   	0x10000
#define OTA_USED_SIZE                   	0x30000

extern int gxirr_start(void);

static unsigned int GxOem_INILoad(char *buf, int size)
{
	return ini_loadmemory(buf, size);
}

static char* GxOem_INIGetValue(unsigned int handle, const char* section, const char* key)
{
	char* value;

	if (!handle) {
		printf("handle error in %s\n", __FUNCTION__);
		return NULL;
	}

	value = ini_get(handle, section, key);

	return value;
}

static int GxOem_INISetValue(unsigned int handle, const char* section,
		const char* key, const char* value)
{
	int ret = 0;

	if (!handle) {
		printf("handle error in %s\n", __FUNCTION__);
		return -1;
	}

	ret = ini_set(handle, section, key, value);

	return ret;
}

static int GxOem_INISave(unsigned int handle, char* buf, int size)
{
	if (!handle) {
		printf("handle error in %s\n", __FUNCTION__);
		return -1;
	}
	memset(buf, 0, size);
	size = ini_savememory(handle, buf, size);

	return size;
}

int gxota_find(void)
{
	u32 flash_size;
	struct partition_info *partition;

	flash_size     	= gxflash_getsize();
	partition 		= malloc(sizeof(struct partition_info));
	strcpy(partition->name, "OTA");
	partition->total_size = OTA_USED_SIZE;
	partition->start_addr = OTA_FIND_START_ADDR;
	do{
		doboot_kernel(partition);
		partition->start_addr += OTA_FIND_STEP;
	}while (partition->start_addr < flash_size);

	printf("No found OTA.\r\n");

	return -1;
}

void gxota_entry(void)
{
	char   *pflag;
	struct partition_info* partition_ota;
	unsigned int oem_handle;
	char *pv_oem = NULL;
	u32  v_oem_size = 0;
	struct partition_info* partition_v_oem;

	partition_ota = all_partition_get(PARTITION_OTA);
	if(NULL == partition_ota){
		if(gxota_find() < 0){
			printf("no ota code bin, please check flash.\n");
			while(1);
		}
	}

#ifdef CONFIG_ENABLE_IRR
	if(gxirr_start())
		doboot_kernel(partition_ota);
#endif

	extern int panel_update_call(void);
	if(panel_update_call() == 0)
		doboot_kernel(partition_ota);

	partition_v_oem = all_partition_get(PARTITION_V_OEM);
	if(partition_v_oem == NULL){

		GXOTA_DBG("v_oem is NULL\r\n");
		return;
	}
	else{
		v_oem_size = partition_v_oem->partition_size;
	}

	pv_oem = malloc(v_oem_size);
	memset(pv_oem, 0, v_oem_size);
	partition_read(partition_v_oem, 0, pv_oem, v_oem_size);

	oem_handle = GxOem_INILoad(pv_oem, v_oem_size);
	pflag = GxOem_INIGetValue(oem_handle, OEM_UPDATE_SECTION, OEM_UPDATE_FLAG);
	//_test_ota(pflag);
	if (pflag){

		GXOTA_DBG("pflag = %s \r\n",  pflag);
        
		if (strncmp(pflag, OEM_UPDATE_VARIABLE,
					strlen(OEM_UPDATE_VARIABLE)) == 0)
			doboot_kernel(partition_ota);
        
		free(pflag);
	} else{
		printf("pflag=%d, will not enter ota.\n", pflag);
	}
}

